spring:
  redis:
    lettuce:
      pool:
        max-active: '10'
        max-idle: '10'
        min-idle: '2'
    host: 127.0.0.1
    port: '6379'

oracle:
  spring:
    jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      generate-ddl: 'true'
      show-sql: 'true'
      hibernate:
        ddl-auto: validate
    datasource:
      hikari:
        jdbc-url: jdbc:log4jdbc:oracle:thin:@10.10.100.14:1521:UNIPG
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: unipg
        password: unipg!
mysql:
  spring:
    jpa:
      database-platform: org.hibernate.dialect.MySQL57Dialect
      generate-ddl: 'true'
      show-sql: 'true'
      hibernate:
        ddl-auto: validate
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://10.10.100.13:3306/testdb?characterEncoding=UTF-8&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: test
        password: test@0212
        connection-init-sql: select 1
logging:
  config: classpath:logback/logback-local.xml
server:
  port: 8080
  servlet:
    context-path: /
ajp-config:
  address: 0.0.0.0
  port: 8015
